// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs3p-DxWHq8QC8QInQq2rtUoE11EcJeWI',
    appId: '1:932994511784:web:7cd1b143c99a2a72bc239d',
    messagingSenderId: '932994511784',
    projectId: 'adda-ghor',
    authDomain: 'adda-ghor.firebaseapp.com',
    storageBucket: 'adda-ghor.appspot.com',
    measurementId: 'G-P8W6953GV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALMAS4uzR9IPKhvtpEDpWQVBnzvzPrKas',
    appId: '1:932994511784:android:cfcf116dd35df163bc239d',
    messagingSenderId: '932994511784',
    projectId: 'adda-ghor',
    storageBucket: 'adda-ghor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8RxLhelgfuNTTqeejNOZ1xFhSZ2wg1kM',
    appId: '1:932994511784:ios:963a1418fda2bc22bc239d',
    messagingSenderId: '932994511784',
    projectId: 'adda-ghor',
    storageBucket: 'adda-ghor.appspot.com',
    androidClientId: '932994511784-1ficru11qtngqvgrf293jacff943133m.apps.googleusercontent.com',
    iosClientId: '932994511784-tcbgved0cco7806jtq7n04gnqru6kij8.apps.googleusercontent.com',
    iosBundleId: 'site.ritom.adda',
  );
}
