name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
      - master

    # on: push    # Default will run for every branch.

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      - run: flutter build ios --debug --no-codesign
#
#      # Upload generated apk to the artifacts.
#      - uses: actions/upload-artifact@v1
#        with:
#          name: release-apk
#          path: build/app/outputs/apk/release/app-release.apk