name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
      - master

    # on: push    # Default will run for every branch.

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      - run: flutter build ios --debug --no-codesign
      - uses: actions/upload-artifact@v2
        with:
          name: release-ipa
          path: Payload.ipa
      - run : mkdir payload
      - run: cp -R build/ios/iphoneos/Runner.app payload/
      - run: zip -r -y payload.zip payload/Runner.app
      - run : mv Payload.zip Payload.ipa
      - uses: actions/upload-artifact@v2
        with:
          name: release-ipa
          path: Payload.ipa